name: ai-ecg-lvh
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - imbalanced-learn=0.13.0
  - matplotlib=3.10.0
  - numba=0.61.0
  - numexpr=2.10.1
  - numpy-base=2.1.3
  - pandas=2.2.3
  - pip=25.0
  - pyarrow=16.1.0
  - pyparsing=3.2.0
  - python=3.11.11
  - scikit-learn=1.6.1
  - scipy=1.15.1
  - seaborn=0.13.2
  - shap=0.47.1
  - sklearn-compat=0.1.3
  - statsmodels=0.14.4
  - tabulate=0.9.0
  - tqdm=4.67.1
  - typing_extensions=4.12.2
  - typing_utils=0.1.0
  - pip:
      - confidenceinterval==1.0.5
      - numpy==2.1.2
      - setuptools==68.2.2
      - sympy==1.13.1
      - torch==2.6.0+cpu
      - torchaudio==2.6.0+cpu
      - torchvision==0.21.0+cpu
